---
- name: "Install xpaste playbook"
  hosts: "all"
  become: true
  vars:
    xpaste_key_base: "a1c80a36-1f3c-44ab-b622-896631c4d351"
    xpaste_ssh_privkey: "{{ lookup('env','HOME') + '/.ssh/id_ed25519_slurm' }}"
    xpaste_db_name: "xpaste_db"
    xpaste_db_user: "xpaste_user"
    xpaste_db_password: "xpastepass"
    postgresql_db_name: "{{ xpostgresql_db_name }}"
    postgresql_db_user: "{{ xpaste_db_user }}"
    postgresql_db_password: "{{ xxpaste_db_password }}"

  roles:
    - "postgresql"
    - "xpaste"
    - "nginxinc.nginx"

  tasks:
    - name: "Install nginx config"
      ansible.builtin.copy:
        src: "{{ xpaste_destdir }}/config/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        remote_src: true
      notify: "Restart nginx"

  handlers:
    - name: "Restart nginx"
      ansible.builtin.service:
        name: "nginx"
        state: "restarted"