---
- name: "Install postgresql"
  ansible.builtin.yum:
    name:
      - "postgresql"
      - "postgresql-server"
      - "python3-psycopg2"
    update_cache: true
    state: present

- name: "Is postgresql configured"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_conf

- name: "Initialize PostgreSQL"
  ansible.builtin.command: "/usr/bin/postgresql-setup --initdb"
  when: not postgres_conf.stat.exists

- name: "Start postgresql"
  ansible.builtin.service:
    name: "postgresql"
    state: "started"
    enabled: true

- name: "Create DB"
  community.postgresql.postgresql_db:
    name: "{{ xpaste_db_name }}"
  become_user: "postgres"

- name: "Create user"
  community.postgresql.postgresql_user:
    db: "{{ xpaste_db_name }}"
    name: "{{ xpaste_db_user }}"
    password: "{{ xpaste_db_password }}"
  become_user: "postgres"
