---
- name: "Install postgresql"
  ansible.builtin.apt:
    name:
      - "postgresql"
      - "postgresql-client"
      - "python3-psycopg2"
      - "acl"
    update_cache: true
    state: "present"

- name: "Start postgresql"
  ansible.builtin.service:
    name: "postgresql"
    state: "started"
    enabled: true

- name: "Create DB"
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db_name }}"
  become_user: "postgres"

- name: "Create user"
  community.postgresql.postgresql_user:
    db: "{{ postgresql_db_name }}"
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
  become_user: "postgres"
