---
- name: "Install dependencies"
  ansible.builtin.apt:
    name:
      - "ruby"
      - "libxml2-dev"
      - "git"
      - "ruby-dev"
      - "libxslt-dev"
      - "nodejs"
      - "libpq-dev"
    update_cache: true
    state: "present"

- name: "Install build-essential"
  ansible.builtin.apt:
    name: "build-essential"
    update_cache: true
    state: "present"

- name: "Set ssh key for slurm gitlab"
  ansible.builtin.copy:
    src: "{{ xpaste_ssh_privkey }}"
    dest: "{{ xpaste_privkey_path }}"
    owner: "root"
    group: "root"
    mode: "0600"

- name: "Get xpaste app"
  ansible.builtin.git:
    repo: "git@gitlab.slurm.io:edu/xpaste_practicum.git"
    dest: "{{ xpaste_destdir }}"
    key_file: "{{ xpaste_privkey_path }}"
    accept_hostkey: true
  notify: "Start xpaste"

- name: "Install bundler"
  community.general.gem:
    name: "bundler"
    version: "{{ xpaste_bundler_version }}"
    state: "present"
    user_install: false

- name: "Restore rake to pristine condition"
  ansible.builtin.command: "gem pristine rake"

- name: "Install pkg-config"
  community.general.gem:
    name: "pkg-config"
    state: "present"
    user_install: false

- name: "Restore minitest to pristine condition"
  ansible.builtin.command: "gem pristine minitest"

- name: "Install ruby dependencies"
  ansible.builtin.shell: "bundle config build.nokogiri --use-system-libraries && bundle install --clean --force --no-cache --without development"
  args:
    chdir: "{{ xpaste_destdir }}"

- name: "Configure app"
  ansible.builtin.template:
    src: "xpaste.j2"
    dest: "/etc/default/xpaste"
    mode: "0644"
  notify: "Start xpaste"

- name: "Create directory for systemd service"
  ansible.builtin.file:
    path: "/usr/local/lib/systemd/system"
    state: directory
    mode: '0755'

- name: "Install systemd service"
  ansible.builtin.template:
    src: "xpaste.service.j2"
    dest: "/usr/local/lib/systemd/system/xpaste.service"
    mode: "0644"
  notify: "Start xpaste"
